name: "pre MR check"

on:
  pull_request_target:
    types:
      - opened
      - edited


jobs:
  master-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: |
            echo "working"