name: "pre MR check"

on:
  issue_comment:
  pull_request:
    branches:
      - master
      - staging
      - pre-prod
    types:
      - opened
      - edited
      - assigned
      - unassigned
      - labeled
      - unlabeled


jobs:
  master-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: |
            echo "working"